/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

/**
 *
 * @author arele
 */
public class VtnPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VtnPrincipal
     */
    public VtnPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuBar1 = new javax.swing.JMenuBar();
        MnuPerecedero = new javax.swing.JMenu();
        mnuAltas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuBajas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuConsultas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuModificaciones = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MnunoPerecedero = new javax.swing.JMenu();
        mnuAltas1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuBajas1 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuConsultas1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnuModificaciones1 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        MnuSalir = new javax.swing.JMenu();
        mnuSSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu para manejo de productos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MnuPerecedero.setText("Perecedero");
        MnuPerecedero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuAltas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuAltas.setText("Altas");
        MnuPerecedero.add(mnuAltas);
        MnuPerecedero.add(jSeparator1);

        mnuBajas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBajas.setText("Bajas");
        MnuPerecedero.add(mnuBajas);
        MnuPerecedero.add(jSeparator2);

        mnuConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsultas.setText("consultas");
        mnuConsultas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuConsultasActionPerformed(evt);
            }
        });
        MnuPerecedero.add(mnuConsultas);
        MnuPerecedero.add(jSeparator3);

        mnuModificaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuModificaciones.setText("Modificaciones");
        MnuPerecedero.add(mnuModificaciones);
        MnuPerecedero.add(jSeparator4);

        jMenuBar1.add(MnuPerecedero);

        MnunoPerecedero.setText("No Perecedero");

        mnuAltas1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuAltas1.setText("Altas");
        MnunoPerecedero.add(mnuAltas1);
        MnunoPerecedero.add(jSeparator5);

        mnuBajas1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBajas1.setText("Bajas");
        MnunoPerecedero.add(mnuBajas1);
        MnunoPerecedero.add(jSeparator6);

        mnuConsultas1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsultas1.setText("consultas");
        MnunoPerecedero.add(mnuConsultas1);
        MnunoPerecedero.add(jSeparator7);

        mnuModificaciones1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuModificaciones1.setText("Modificaciones");
        MnunoPerecedero.add(mnuModificaciones1);
        MnunoPerecedero.add(jSeparator8);

        jMenuBar1.add(MnunoPerecedero);

        MnuSalir.setText("Salir");

        mnuSSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSSalir.setText("salir");
        mnuSSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        mnuSSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuSSalirActionPerformed(evt);
            }
        });
        MnuSalir.add(mnuSSalir);

        jMenuBar1.add(MnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuSSalirActionPerformed
    {//GEN-HEADEREND:event_mnuSSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_mnuSSalirActionPerformed

    private void mnuConsultasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuConsultasActionPerformed
    {//GEN-HEADEREND:event_mnuConsultasActionPerformed
      new Vtnpc.setVisible(true) ; // TODO add your handling code here:
    }//GEN-LAST:event_mnuConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuPerecedero;
    private javax.swing.JMenu MnuSalir;
    private javax.swing.JMenu MnunoPerecedero;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JMenuItem mnuAltas;
    private javax.swing.JMenuItem mnuAltas1;
    private javax.swing.JMenuItem mnuBajas;
    private javax.swing.JMenuItem mnuBajas1;
    private javax.swing.JMenuItem mnuConsultas;
    private javax.swing.JMenuItem mnuConsultas1;
    private javax.swing.JMenuItem mnuModificaciones;
    private javax.swing.JMenuItem mnuModificaciones1;
    private javax.swing.JMenuItem mnuSSalir;
    // End of variables declaration//GEN-END:variables
}
