/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

import cjb.ci.Mensaje;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import s3.ManipulaArchivos;
import s3.NoPerecederos;
import s3.Perecederos;
import s3.Productos;

/**
 *
 * @author Mauro Sanchez2
 */
public class VtnP extends javax.swing.JFrame
{

    public static Productos p[] = null;

    /**
     * Creates new form VtnP
     */
    public VtnP()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jtbP = new javax.swing.JToolBar();
        tgbPA = new javax.swing.JToggleButton();
        tgbPB = new javax.swing.JToggleButton();
        tgbPC = new javax.swing.JToggleButton();
        tgbPM = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPerecederos = new javax.swing.JMenu();
        mnuPAltas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuPBajas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuPConsultas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuPModificaciones = new javax.swing.JMenuItem();
        mnuNoPerecederos = new javax.swing.JMenu();
        mnuNPAltas = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuNPBajas = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuNPConsultas = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnuNPModificaciones = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mnuSSalir = new javax.swing.JMenuItem();
        mnuChBP = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menú para manejo de productos ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jtbP.setRollover(true);

        tgbPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lapiz.jpg"))); // NOI18N
        tgbPA.setToolTipText("alta de productos perecederos");
        tgbPA.setFocusable(false);
        tgbPA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tgbPA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tgbPA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tgbPAActionPerformed(evt);
            }
        });
        jtbP.add(tgbPA);

        tgbPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goma.jpg"))); // NOI18N
        tgbPB.setToolTipText("bajas de productos perecederos");
        tgbPB.setFocusable(false);
        tgbPB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tgbPB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tgbPB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tgbPBActionPerformed(evt);
            }
        });
        jtbP.add(tgbPB);

        tgbPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        tgbPC.setToolTipText("consultas de productos perecederos");
        tgbPC.setFocusable(false);
        tgbPC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tgbPC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tgbPC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tgbPCActionPerformed(evt);
            }
        });
        jtbP.add(tgbPC);

        tgbPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libreta.jpg"))); // NOI18N
        tgbPM.setToolTipText("modificaciones de productos perecederos");
        tgbPM.setFocusable(false);
        tgbPM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tgbPM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tgbPM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tgbPMActionPerformed(evt);
            }
        });
        jtbP.add(tgbPM);

        mnuPerecederos.setText("Perecederos");

        mnuPAltas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuPAltas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lapiz16.jpg"))); // NOI18N
        mnuPAltas.setText("Altas");
        mnuPAltas.setToolTipText("alta de productos perecederos");
        mnuPAltas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPAltas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuPAltasActionPerformed(evt);
            }
        });
        mnuPerecederos.add(mnuPAltas);
        mnuPerecederos.add(jSeparator1);

        mnuPBajas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuPBajas.setText("Bajas");
        mnuPBajas.setToolTipText("bajas de productos perecederos");
        mnuPBajas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPBajas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuPBajasActionPerformed(evt);
            }
        });
        mnuPerecederos.add(mnuPBajas);
        mnuPerecederos.add(jSeparator2);

        mnuPConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuPConsultas.setText("Consultas");
        mnuPConsultas.setToolTipText("consultas de productos perecederos");
        mnuPConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPConsultas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuPConsultasActionPerformed(evt);
            }
        });
        mnuPerecederos.add(mnuPConsultas);
        mnuPerecederos.add(jSeparator3);

        mnuPModificaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuPModificaciones.setText("Modificaciones");
        mnuPModificaciones.setToolTipText("modificaciones de productos perecederos");
        mnuPModificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPModificaciones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuPModificacionesActionPerformed(evt);
            }
        });
        mnuPerecederos.add(mnuPModificaciones);

        jMenuBar1.add(mnuPerecederos);

        mnuNoPerecederos.setText("No Perecederos");

        mnuNPAltas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        mnuNPAltas.setText("Altas");
        mnuNPAltas.setToolTipText("alta de productos no perecederos");
        mnuNPAltas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuNoPerecederos.add(mnuNPAltas);
        mnuNoPerecederos.add(jSeparator5);

        mnuNPBajas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        mnuNPBajas.setText("Bajas");
        mnuNPBajas.setToolTipText("bajas de productos no perecederos");
        mnuNPBajas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuNoPerecederos.add(mnuNPBajas);
        mnuNoPerecederos.add(jSeparator6);

        mnuNPConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mnuNPConsultas.setText("Consultas");
        mnuNPConsultas.setToolTipText("consultas de productos no perecederos");
        mnuNPConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuNPConsultas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuNPConsultasActionPerformed(evt);
            }
        });
        mnuNoPerecederos.add(mnuNPConsultas);
        mnuNoPerecederos.add(jSeparator7);

        mnuNPModificaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        mnuNPModificaciones.setText("Modificaciones");
        mnuNPModificaciones.setToolTipText("modificaciones de productos no perecederos");
        mnuNPModificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuNPModificaciones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuNPModificacionesActionPerformed(evt);
            }
        });
        mnuNoPerecederos.add(mnuNPModificaciones);

        jMenuBar1.add(mnuNoPerecederos);

        mnuSalir.setText("Salir");

        mnuSSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSSalir.setText("Salir");
        mnuSSalir.setToolTipText("salir del programa");
        mnuSSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuSSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuSSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuSSalir);

        mnuChBP.setSelected(true);
        mnuChBP.setText("Perecederos");
        mnuChBP.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                mnuChBPStateChanged(evt);
            }
        });
        mnuSalir.add(mnuChBP);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbP, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 451, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 379, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuSSalirActionPerformed
    {//GEN-HEADEREND:event_mnuSSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuSSalirActionPerformed

    private void mnuPConsultasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuPConsultasActionPerformed
    {//GEN-HEADEREND:event_mnuPConsultasActionPerformed
        new VtnPC().setVisible(true);
    }//GEN-LAST:event_mnuPConsultasActionPerformed

    private void mnuNPConsultasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuNPConsultasActionPerformed
    {//GEN-HEADEREND:event_mnuNPConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNPConsultasActionPerformed

    private void mnuNPModificacionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuNPModificacionesActionPerformed
    {//GEN-HEADEREND:event_mnuNPModificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNPModificacionesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        p = (Productos[]) ManipulaArchivos.carga("datos1.dat");
    }//GEN-LAST:event_formWindowOpened

    private void mnuPAltasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuPAltasActionPerformed
    {//GEN-HEADEREND:event_mnuPAltasActionPerformed
        VtnPA vPA = new VtnPA();
        vPA.setVisible(true);
    }//GEN-LAST:event_mnuPAltasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void mnuPBajasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuPBajasActionPerformed
    {//GEN-HEADEREND:event_mnuPBajasActionPerformed
        new VtnPB().setVisible(true);
    }//GEN-LAST:event_mnuPBajasActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        ManipulaArchivos.guarda(p, "datos1.dat");
    }//GEN-LAST:event_formWindowClosed

    private void mnuPModificacionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuPModificacionesActionPerformed
    {//GEN-HEADEREND:event_mnuPModificacionesActionPerformed
        new VtnPM().setVisible(true);
    }//GEN-LAST:event_mnuPModificacionesActionPerformed

    private void tgbPAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tgbPAActionPerformed
    {//GEN-HEADEREND:event_tgbPAActionPerformed
        mnuPAltasActionPerformed(evt);
    }//GEN-LAST:event_tgbPAActionPerformed

    private void tgbPBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tgbPBActionPerformed
    {//GEN-HEADEREND:event_tgbPBActionPerformed
        mnuPBajasActionPerformed(evt);
    }//GEN-LAST:event_tgbPBActionPerformed

    private void tgbPCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tgbPCActionPerformed
    {//GEN-HEADEREND:event_tgbPCActionPerformed
        mnuPConsultasActionPerformed(evt);
    }//GEN-LAST:event_tgbPCActionPerformed

    private void tgbPMActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tgbPMActionPerformed
    {//GEN-HEADEREND:event_tgbPMActionPerformed
        mnuPModificacionesActionPerformed(evt);
    }//GEN-LAST:event_tgbPMActionPerformed

    private void mnuChBPStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_mnuChBPStateChanged
    {//GEN-HEADEREND:event_mnuChBPStateChanged
        if (jtbP.isEnabled())
        {
            jtbP.setEnabled(false);
            jtbP.setVisible(false);
        } else
        {
            jtbP.setEnabled(true);
            jtbP.setVisible(true);
        }
    }//GEN-LAST:event_mnuChBPStateChanged

    private void formFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_formFocusGained
    {//GEN-HEADEREND:event_formFocusGained
        activaMNU(mnuPBajas,mnuPConsultas,mnuPModificaciones);
        activaTGB(tgbPB,tgbPC,tgbPM);
    }//GEN-LAST:event_formFocusGained

    public static void activaMNU(JMenuItem ... objs)
    {
        boolean b=true;
        if(p == null)
        {
            b=false;
        }
        for (int i = 0; i < objs.length; i++)
        {
            objs[i].setEnabled(b);
        }
    }
    
    public static void activaTGB(JToggleButton ... objs)
    {
        boolean b=true;
        if(p == null)
        {
            b=false;
        }
        for (int i = 0; i < objs.length; i++)
        {
            objs[i].setEnabled(b);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnP().setVisible(true);
            }
        });
    }

    public static int busca(int opc, String s, JFrame jf)
    {
        if (p == null)
        {
            Mensaje.error(jf, "No hay datos almacenados...");
        } else
        {
            String nom = JOptionPane.showInputDialog(jf,
                    "dame el nombre a " + s + " :");
            if (nom != null)
            {
                for (int i = 0; i < p.length; i++)
                {
                    if (p[i] instanceof Perecederos
                            && opc == 1 && nom.equals(p[i].getNom()))
                    {
                        return i;
                    } else
                    {
                        if (p[i] instanceof NoPerecederos
                                && opc == 2 && nom.equals(p[i].getNom()))
                        {
                            return i;
                        }
                    }
                }
                Mensaje.error(jf, "Dato no encontrado...");
            }
        }
        return -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jtbP;
    private javax.swing.JCheckBoxMenuItem mnuChBP;
    private javax.swing.JMenuItem mnuNPAltas;
    private javax.swing.JMenuItem mnuNPBajas;
    private javax.swing.JMenuItem mnuNPConsultas;
    private javax.swing.JMenuItem mnuNPModificaciones;
    private javax.swing.JMenu mnuNoPerecederos;
    private javax.swing.JMenuItem mnuPAltas;
    private javax.swing.JMenuItem mnuPBajas;
    private javax.swing.JMenuItem mnuPConsultas;
    private javax.swing.JMenuItem mnuPModificaciones;
    private javax.swing.JMenu mnuPerecederos;
    private javax.swing.JMenuItem mnuSSalir;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JToggleButton tgbPA;
    private javax.swing.JToggleButton tgbPB;
    private javax.swing.JToggleButton tgbPC;
    private javax.swing.JToggleButton tgbPM;
    // End of variables declaration//GEN-END:variables
}
