/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import poo.bd.Querys;
import s3.ManipulaProductos;
import s3.Perecederos;

/**
 *
 * @author Mauro Sanchez2
 */
public class VtnPB extends javax.swing.JFrame
{

    int pos = -1;

    /**
     * Creates new form VtnPA
     */
    public VtnPB()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfExistenacias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfFechaCad = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja de productos perecederos");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Nombre :");

        tfNombre.setEnabled(false);
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfNombreKeyTyped(evt);
            }
        });

        jLabel2.setText("Existencias:");

        tfExistenacias.setEnabled(false);
        tfExistenacias.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfExistenaciasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfExistenaciasKeyTyped(evt);
            }
        });

        jLabel3.setText("Fecha de caduciodad:");

        tfFechaCad.setEnabled(false);
        tfFechaCad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfFechaCadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfFechaCadKeyTyped(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Buscar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfFechaCad))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfExistenacias, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(103, 103, 103))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfExistenacias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFechaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        if (btnAceptar.getText().equals("Buscar"))
        {
            String nom = JOptionPane.showInputDialog(this,
                    "dame el nombre a eliminar :");
            Connection con = ManipulaDB.conecta(this);
            if (con != null)
            {
                Querys sql = new Querys();
                ArrayList<Perecederos> ap = ManipulaDB.cargaP(sql.Seleccion(con, "*", "Perecederos", "nombre='" + nom.trim() + "'"));
                ManipulaDB.desconecta(con);
                if (ap != null)
                {
                    tfNombre.setText(ap.get(0).getNom());
                    tfExistenacias.setText(String.valueOf(ap.get(0).getExistencias()));
                    tfFechaCad.setText( ap.get(0).getFechaCad());
                    btnAceptar.setText("Eliminar");
                }else
                {
                    Mensaje.error(this, "Dato no encontrado");
                }
            }
        } else
        {
            if (Mensaje.pregunta(this, "¿desea eliminar este registro?") == 0)
            {
                Connection con = ManipulaDB.conecta(this);
                if (con != null)
                {
                     Querys sql = new Querys();
                     sql.Delete(con, "Perecederos", "nombre", "'"+tfNombre.getText().trim()+"'");
                     ManipulaDB.desconecta(con);
                     Mensaje.exito(this, "Dato eliminado correctamente");
                }
            }
            btnCancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        CtrlInterfaz.limpia(tfNombre, tfExistenacias, tfFechaCad);
        CtrlInterfaz.habilita(false, tfExistenacias, tfFechaCad, tfNombre);
        btnAceptar.setText("Buscar");
        CtrlInterfaz.cambia(btnAceptar);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombreKeyTyped
    {//GEN-HEADEREND:event_tfNombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNombreKeyPressed
    {//GEN-HEADEREND:event_tfNombreKeyPressed
        Validaciones.enter(this, evt, tfExistenacias);
    }//GEN-LAST:event_tfNombreKeyPressed

    private void tfExistenaciasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfExistenaciasKeyTyped
    {//GEN-HEADEREND:event_tfExistenaciasKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_tfExistenaciasKeyTyped

    private void tfExistenaciasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfExistenaciasKeyPressed
    {//GEN-HEADEREND:event_tfExistenaciasKeyPressed
        Validaciones.enterEntero(this, evt, tfExistenacias, tfFechaCad);
    }//GEN-LAST:event_tfExistenaciasKeyPressed

    private void tfFechaCadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfFechaCadKeyTyped
    {//GEN-HEADEREND:event_tfFechaCadKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_tfFechaCadKeyTyped

    private void tfFechaCadKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfFechaCadKeyPressed
    {//GEN-HEADEREND:event_tfFechaCadKeyPressed
        Validaciones.enter(this, evt, btnAceptar);
    }//GEN-LAST:event_tfFechaCadKeyPressed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPB().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfExistenacias;
    private javax.swing.JTextField tfFechaCad;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
